### ISSUE TITLE
Mysql blocking request

### ISSUE THREAD

**Issue by Julienh** [PyMySQL/mysqlclient#464]
Hello,

I spent few hours to try to fix a problem I thought was because of Bottle or FastApi :
With this code:
```
# -*- coding: utf-8 -*-
import MySQLdb
from bottle import route, run
from gevent import monkey
monkey.patch_all()


cnx = MySQLdb.connect(host='127.0.0.1', port=3306, db='db', user='user', passwd='pass', use_unicode=True, charset="utf8mb4")
cursor = cnx.cursor()


@route('/testlong', method='GET')
def test_long():
    cursor.execute('SELECT SLEEP(5);')
    return 'finished'


@route('/testfast', method='GET')
def test_fast():
    return 'finished'


if __name__ == '__main__':
    run(host='127.0.0.1', port=46677, debug=True, server='gevent')
```

If I run http://localhost:46677/testlong and at the same moment http://localhost:46677/testfast on a different browser, my second request have to wait that the first is finished (so 5 seconds).

But if I try with pymysql it's working ! What am I missing please ?

**Comment by methane** [comment]
I can explain it but I won't. If you can not understand it, you must not use gevent.

**Comment by methane** [comment]
http://csrgxtu.github.io/2020/04/16/Gevent-patch-it-and-pray/
