### ISSUE TITLE
TODO for v3.0

### ISSUE THREAD

**Issue by methane** [PyMySQL/mysqlclient#473]
- [ ] Use keyword only arguments

**Comment by glasshex** [comment]
Removing `*args` in the initialization function would make python require exactly one positional argument (self), the rest keyword arguments:
https://github.com/PyMySQL/mysqlclient/blob/main/MySQLdb/connections.py#L56

Also for functions such as this: https://github.com/PyMySQL/mysqlclient/blob/main/MySQLdb/connections.py#L250
I think it's possible to force python to require "query" argument to be keyword-only by modifying it to something like:
`def query(self, *, query):`

Am I understanding this item correctly? I'm interested in taking a shot at it if so.
