### ISSUE TITLE
Building mysqlclient on Windows is very hard. But there are some binary wheels you can install easily.

### ISSUE THREAD

**Issue by juancroldan** [PyMySQL/mysqlclient#480]
That's a statement from the README.md. Is that really all that's possible to explain? Probably a install of chocolatey with a couple of VCRedist dependencies would suffice.

**Comment by methane** [comment]
> Is that really all that's possible to explain?

Yes, that's all what I can explain *and maintain*.

> Probably a install of chocolatey with a couple of VCRedist dependencies would suffice.

It's impossible. I'm not a Wndows user.
