### ISSUE TITLE
Column values generated by window functions are returned as bytes, instead of str

### ISSUE THREAD

**Issue by dprien** [PyMySQL/mysqlclient#481]
### Describe the bug

Column values generated by window functions (at least `FIRST_VALUE` and `LAST_VALUE`) are returned as `bytes`, even though the column's underlying type is `VARCHAR(255)` and the table's default charset is `utf8`.

### To Reproduce

```sql
CREATE TABLE test_table (a VARCHAR(255) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO test_table (a) VALUES ('foo'),('bar');
```

**Code**

```py
con = MySQLdb.connect(...)
cur = con.cursor()
cur.execute("SELECT a, FIRST_VALUE(a) OVER (ORDER BY a) FROM test_table")
for row in c.fetchall():
    print(row)
```

**Output**
```
('bar', b'bar')
('foo', b'bar')
```

Notice the `b'...'` byte-string literal markers in the second column.

### Environment

**MySQL Server**

- Server OS: `CentOS 7.6.1810`
- Server Version: `MariaDB 10.2.25-1.el7.centos`

**MySQL Client**

- OS: `Ubuntu 20.04.1 LTS`
- Python: `Python 3.8.5`
- Connector/C: `mysqlclient 2.0.3` (installed via pip, linked against `libmariadb3 10.3.22-1ubuntu1`)

**Comment by methane** [comment]
Thank you reporting. But the client don't decide column type. The column type is decided by server.
Try latest server version, and report it to MariDB if it is not fixed yet.
