### ISSUE TITLE
mysql_user module issue with utf8 char like "£"

### ISSUE THREAD

**Issue by emper0r** [PyMySQL/mysqlclient#492]
### Describe the bug
Using mysql_user.py module to add new user into database:
- on centos 7, I can send password with '£' symbol in the string, python interprete that as unicode '\u00a3' wichi is '£' symbol and on MySQL I can see when receive data with correct '£'
```
SELECT CONCAT('*', UCASE(SHA1(UNHEX(SHA1('abc123£abc123')))))
```
- on Centos 8, that symbol comes into other character, using same settings on both servers utf8.
```
SELECT CONCAT('*', UCASE(SHA1(UNHEX(SHA1('abc123| abc123'))))) 
```

### To Reproduce
https://github.com/ansible-collections/community.mysql/blob/main/plugins/modules/mysql_user.py#L468

**MySQL Server**

- Server OS: CentOS 8
- Server Version: 5.7.33-36

**MySQL Client**
- OS: CentOS 8
- Python: 3.8: python3-mysql-1.4.6-5.el8.x86_64
- Connector/C: mariadb-connector-c-3.1.11-2.el8_3.x86_64 

### Additional context
https://github.com/ansible-collections/community.mysql/issues/140

**Comment by methane** [comment]
If you want to use non-ASCII charactor, you should use `charset="utf8mb4"` option.
