### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 0: character maps to <undefined>

### ISSUE THREAD

**Issue by vkick** [PyMySQL/mysqlclient#498]
### Describe the bug

I'm getting the following error message when trying to query (SELECT * FROM foo) a table with the latin1 character sets:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 0: character maps to <undefined>

Here is the stack trace from running on python3:

[]#  python3 mysqlconn.py
()
Traceback (most recent call last):
  File "mysqlconn.py", line 8, in <module>
    cur.execute("SELECT c FROM foo")
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 321, in _query
    self._post_get_result()
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 355, in _post_get_result
    self._rows = self._fetch_row(0)
  File "/usr/local/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 328, in _fetch_row
    return self._result.fetch_row(size, self._fetch_type)
  File "/usr/lib64/python3.6/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 0: character maps to <undefined>

[]# pip3 show mysqlclient
Name: mysqlclient
Version: 2.0.3

This does not happen on the python2.7 MySQLdb module.

[]# python2 mysqlconn.py
()
((u'~',), (u'\x7f',), (u'\x80',), (u'\x81',), (u'\x82',))

python2's MySQLdb
>>> import MySQLdb
>>> MySQLdb.__version__
'1.2.5'

### To Reproduce

**Schema**

```
CREATE TABLE `foo` (
  `c` varchar(4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

**Code**

```
import MySQLdb
conn = MySQLdb.connect(host="<ip address>", user="root", db="test", port=<port>,
                       use_unicode=True, charset="latin1")
conn.autocommit(True)
cur = conn.cursor()
cur.execute("DROP TABLE IF EXISTS foo")
cur.execute("""CREATE TABLE `foo` (
  `c` varchar(4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1""")
cur.execute("INSERT INTO foo (c) VALUES (0x7e),(0x7f),(0x80),(0x81),(0x82)")
print(cur.fetchall())
cur.execute("SELECT c FROM foo")
print(cur.fetchall())
```

### Environment

**MySQL Server**

- Server OS: 
[]# cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)

- Server Version :
MariaDB [test]> select version();
+----------------+
| version()      |
+----------------+
| 10.5.5-MariaDB |
+----------------+
1 row in set (0.000 sec)

**MySQL Client**

- OS:
CentOS Linux release 7.8.2003 (Core)
- Python:
- Python 3.6.8
- Connector/C (e.g. Homebrew mysql-client 8.0.18):

**Comment by methane** [comment]
0x81 is not defined in latin1. You should use binary or UTF-8.

**Comment by alfonsrv** [comment]
How does one use `binary`?
