### ISSUE TITLE
No link to releases on the main project page

### ISSUE THREAD

**Issue by sbraz** [PyMySQL/mysqlclient#499]
**Describe the bug**
Hi,
There is no link to https://github.com/PyMySQL/mysqlclient/releases on https://github.com/PyMySQL/mysqlclient

![image](https://user-images.githubusercontent.com/4833332/130133647-06d5789b-7923-4cf4-ae55-a49808be5342.png)

**To Reproduce**
Visit https://github.com/PyMySQL/mysqlclient

**Expected behavior**
There should be a "Releases" link under "MIT License" since `v2.0.1` is a release, not just a tag.

**Comment by methane** [comment]
It is not a bug.

**Comment by sbraz** [comment]
Hi @methane, thanks for the feedback but why don't you want releases to be visible on the main page?

Also, how do you do it? I looked at one of my project's settings but couldn't find anything.
