### ISSUE TITLE
TypeError: 'db' is an invalid keyword argument for connect()

### ISSUE THREAD

**Issue by jameskirsop** [PyMySQL/mysqlclient#524]
### Describe the bug
Trying to connect produces an incorrect error, which I believe should be resolved by code already in the module (popping off `db` from args) but doesn't seem to be. You'll see below that I'm not passing `db` as a parameter to `.Connect`.

### To Reproduce

In a python 3.8 interpreter / shell run:
```
import MySQLdb
MySQLdb.Connect(charset = 'utf8', user = 'username', database = 'name', password = 'hello', client_flag = 2)
```

### Environment
**MySQL Client**
- OS (e.g. Windows 10, Ubuntu 20.04): CentOS 7
- Python: 3.8.11 (Installed from the centos SCLO repository)
- Connector/C: 10.2.41-1 (installed from the MariaDB repo)

### Additional context

Here's a traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/healthcheck/venv/lib64/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/var/www/healthcheck/venv/lib64/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
TypeError: 'db' is an invalid keyword argument for connect()
```

**Comment by methane** [comment]
This library has huge userbase. I don't think such a bug is alive.
Would you triple check your environment?
And would you reproduce it with Docker?

I won't set up CentOS only for this issue.

**Comment by jameskirsop** [comment]
You were right, I removed the virtualenv entirely, rebuilt it from my `requirements.txt` and the issue disappeared. It was very confusing because it was already a clean virtualenv that I'd built a week ago...

おじかんをわいていただきありがとうがじました
