### ISSUE TITLE
Add UUID type for Mariadb 10.7

### ISSUE THREAD

**Issue by My-Name-Is-Nabil** [PyMySQL/mysqlclient#529]
Documentation here:
https://mariadb.com/kb/en/uuid-data-type/

**Comment by methane** [comment]
From driver's point of view, it is just a string.
Convert from string to `uuid.UUID` or some other type is task of ORM.

**Comment by My-Name-Is-Nabil** [comment]
Wouldn't it be helpful if it was added in /constants/FIELD_TYPE.py ?

**Comment by methane** [comment]
No.
 It can't be distinguished by FIELD_TYPE.

Recent MariaDB returned custom metadata. It can be used to distinguish TEXT
and UUID (and JSON).
But it is not in plain MySQL protocol and it's C API.
I won't support such many custom MariaDB extensions.
You should ask to MariaDB-connector-python instead.

But you should note that using string for UUID (and JSON).
Note that they are all strings in MySQL protocol.
When driver (or connector) return string, converting it into application
data type is job of application or ORM.
You can use UUID and many other types with ORM.


2022年2月12日(土) 20:59 Mohamed Nabil Rady ***@***.***>:

**Comment by My-Name-Is-Nabil** [comment]
Thanks for the constructive reply.
