### ISSUE TITLE
Random issues on windows

### ISSUE THREAD

**Issue by el1s7** [PyMySQL/mysqlclient#544]
Using the mysqlclient on Windows with flask acts in a weird way.

'Out of sync' errors are the most common. Sometimes it returns completely different stuff, like another table. And sometimes it throws column doesn't exist errors when it actually exists and sometimes it just randomly stops.

These issues have always occured to me on Windows 7, Windows 10, Windows 11 during testings.

Though running it on Linux is stable and works how it's supposed to.

Considering the popularity of this library and the people using MySQL, these issues should be addressed. Or at least put some notice on the readme about running on Windows  to save developers some headaches.

**Comment by methane** [comment]
Please provide minimum reproducible example.

**Comment by el1s7** [comment]
> Please provide minimum reproducible example.

Windows, MySQL, Flask. 

What example do you want me to provide?

**Comment by methane** [comment]
Complete step and code to reproduce with minimum code and dependencies.

**Comment by el1s7** [comment]
Looks like the issues were caused by threads. Flask development server was the culprit, that's why the issue only occurred in the local windows environment.
