### ISSUE TITLE
mysqlclient is does not handle new MYSQL connection standards properly

### ISSUE THREAD

**Issue by opzesty** [PyMySQL/mysqlclient#545]
### Describe the bug

MySQL has moved to use cahcing_sha2_password as its default authentication plugin, and does not allow downgrade upon first log in.  mysqlclient is not built to support this authentication plugin, so will fail to connect to a MySQL database that has just been stood up.  This causes issues in a docker environment where standing up a "new" database can happen quite frequently. 

### To Reproduce
Ensure you have docker, docker-compose, and git installed

```
git clone -b error https://github.com/opzesty/sqlalchemy-bug.git
cd sqlalchemy-bug/
docker-compose build
docker-compose up -d database
docker-compose up -d sqlalchemytest
docker logs sqlalchemy-bug_sqlalchemytest_1
```

**Comment by methane** [comment]
Your example uses mysql-connector-python, not this library.

**Comment by opzesty** [comment]
The first commit (tagged with error) uses this library.  The second commit demonstrates the behavior being fixed in the mysql-connector-python library

**Comment by methane** [comment]
Your image is based on Debian.
Debian don't provide MySQL Connector/C. It provides MariaDB Connector/C.
MariaDB Connector/C is API compatible so mysqlclient can use MariaDB Connector.
But MariaDB Connector in Debian doesn't support caching_sha2_password.

You need to install MySQL Connector/C and use it when building mysqlclient.
But I won't provide concrete step for it. Do try-and-error yourself.
