### ISSUE TITLE
tcp socket timeout not working.

### ISSUE THREAD

**Issue by cfrademan** [PyMySQL/mysqlclient#548]
Hi there,

Operating system: Ubuntu 20.04 (LTS), Python version: 3.8.10, mysqlclient version: 2.1.0.

Expected default scenario:
1. DB server goes offline, nothing is listening and nothing is responding, there is not even ARP for the DB server.
2. Application using mysqlclient connects, and hangs forever since TCP connect is just stuck on port 3306. 3. 

Solution: Set the connect keyword arguement of connect_timeout=2 which does not have any affect on MysqlClient.

Problem: Even when setting a connection timeout of 2 seconds on new tcp connection it still hangs.

Impact: 96 servers, have temporary issue conneting to DB server with hundreds of thousands of asyncio tasks and threads all hanging. 

Thank you.

**Comment by methane** [comment]
Your report is unclear and not reproducible.
Anyway, this library doesn't implement timeouts. timeouts are implemented in underlaying libraries (e.g. libmysqlclient or libmariadbclient).
So nothing can be done for you in this library.
