### ISSUE TITLE
https://mysqlclient.readthedocs.io/ documentation is outdated

### ISSUE THREAD

**Issue by matusvalo** [PyMySQL/mysqlclient#552]
### Read this first

We don't use this issue tracker to help users.  If you had trouble, please ask it on some user community. See [here](https://github.com/PyMySQL/mysqlclient-python#support).
Please use this tracker only when you are sure about it is an issue of this software.

And please provide full information from first.  I don't want to ask questions like "What is your Python version?", "Do you confirm MySQL error log?".  If the issue report looks incomplete, I will just close it.

Are you ready?  Please remove until here and make a good issue report!!

### Describe the bug

Documentation in https://mysqlclient.readthedocs.io/  is outdated comparing to the code in repository. The last build is 2 years old:
![image](https://user-images.githubusercontent.com/827060/184371465-8a5904b2-61ae-4bf7-a60b-199c3336883c.png)

So some new functionality (e.g. `ssl_mode` parameter) is present only in source code and easily missed by users.

**Comment by okainov** [comment]
It seems *very* out-of-date, even the connect example is wrong, the actual code will complain for `db` or `passwd` parameters...

**Comment by methane** [comment]
I had changed the default branch name from master to main.
I think it broke the RTD.

**Comment by methane** [comment]
libmysqlclient is needed to build the doc.
So I can not fix the RTD manual.

**Comment by methane** [comment]
I succeeded to build the doc by adding config file.
