### ISSUE TITLE
Manylinux wheels support

### ISSUE THREAD

**Issue by sridhar562345** [PyMySQL/mysqlclient#554]
Most of the packages of publishing many Linux wheels on PyPI. I think it would be better if we also add that support.

**Comment by methane** [comment]
https://github.com/PyMySQL/mysqlclient/issues?q=is%3Aissue+wheel+is%3Aclosed

**Comment by sridhar562345** [comment]
@methane 
Any reason why we aren't able to this?

**Comment by methane** [comment]
Have you read all threads in the search results before asking it?

**Comment by methane** [comment]
https://answers.sap.com/questions/9820973/searching-before-asking---a-discussion-with-your-f.html
