### ISSUE TITLE
Unable to install version 2.1.1 in windows 11

### ISSUE THREAD

**Issue by tamilxpo** [PyMySQL/mysqlclient#558]
![image](https://user-images.githubusercontent.com/81640161/191275082-750c6727-c95f-4680-b1ba-3724b8bc2c92.png)

**Comment by methane** [comment]
Use Python 3.8 or above. I prepared wheels for Python 3.8-3.11.

It is possible to build it manually, but it's hard and I won't help it. You should read error message and fix it by yourself.
