### ISSUE TITLE
PyPi: Update README in pypi.org

### ISSUE THREAD

**Issue by Epic-R-R** [PyMySQL/mysqlclient#670]
Add `pkg-config` in Linux installation guide
`sudo apt-get install python3-dev default-libmysqlclient-dev build-essential `# Debian / Ubuntu
`sudo apt-get install python3-dev default-libmysqlclient-dev build-essential pkg-config` # Debian / Ubuntu

**Comment by methane** [comment]
It is fixed in main branch already.
README in PyPI will be fixed in the next release.
