### ISSUE TITLE
MariaDB?

### ISSUE THREAD

**Issue by robertsilen** [PyMySQL/mysqlclient#719]
Would it be fair to add MariaDB to the repo's description in addition to MySQL? Same for the [documentation](https://mysqlclient.readthedocs.io/)? Considering MariaDB is the default in most distros, and you even mention the MariaDB C connector, it would only be fair to mention MariaDB? Would also remove any compatibility doubts. I can do a PR?

**Comment by methane** [comment]
I updated the repository description.

**Comment by robertsilen** [comment]
> I updated the repository description.

Thanks! I see that now at https://github.com/PyMySQL/mysqlclient

**Comment by robertsilen** [comment]
Would it be appropriate to mention MariaDB in the documentation at https://mysqlclient.readthedocs.io/ ? 
Perhaps add at least to the [user guide's intro ](https://mysqlclient.readthedocs.io/user_guide.html#introduction)"MySQLdb is an interface to the popular MySQL **and MariaDB** database server**s** that provides the Python database API."

**Comment by robertsilen** [comment]
I made a PR now, hope it ok and can be approved? https://github.com/PyMySQL/mysqlclient/pull/720

**Comment by robertsilen** [comment]
https://github.com/PyMySQL/mysqlclient/pull/720 was merged
